version: '2'
services:
    unicorn-runner-app:
        image: enet/unicorn-runner
        volumes:
        - ..:/usr/share/nginx/html
        ports:
        - 127.0.0.1:9220:80
        environment:
        - NGINX_PORT=80
